BUG: Fix creating QMouseEvent in Qt5
QMouseEvent in Qt5 expects its localPos argument to be a QPointF, whereas Qt4
expects its a QPoint. Make creating the QMouseEvent compatible with Qt5. This
fixes an error like the following:

    ValueError: Could not find matching overload for given arguments:
    (5, QPoint (675, 238, at: 0x27ac77f0), 0, 0, 0)