BUG: Fix failing test_LandmarkRegistrationVTKv6Picking due to SampleDataSource constructor
Failing in latest Slicer with error:

```python

ERROR: test_LandmarkRegistrationVTKv6Picking (LandmarkRegistration.LandmarkRegistrationTest)
Test the picking situation on VTKv6

Traceback (most recent call last):
  File "Slicer-build/lib/Slicer-4.11/qt-scripted-modules/LandmarkRegistration.py", line 1089, in test_LandmarkRegistrationVTKv6Picking
    w.volumeDialogSelectors["Fixed"].setCurrentNode(fixed)
TypeError: method requires a VTK object
```

SampleDataSource was changed in
https://github.com/Slicer/Slicer/commit/5d70815798b8f324b2a14ad6e9cfa1634edf9ba9

Co-authored-by: Jean-Christophe Fillion-Robin <jchris.fillionr@kitware.com>