ENH: Make reading of DeveloperMode setting more robust
Similar to the approach in https://github.com/Slicer/Slicer/commit/fba6424, make
reading the DeveloperMode setting more robust. The setting lookup now handles
when the setting doesn't exist and when it returns a bool, as in Qt5. This fixes
the following error:

    AttributeError: 'bool' object has no attribute 'lower'